version: '3.7'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 52607:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  # app:
  #   build: .
  #   container_name: rentx
  #   ports: 
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database
  #   depends_on: 
  #     - database

volumes:
  pgdata:
    driver: local